application: flyingsim
version: 1
runtime: python
api_version: 1

handlers:
- url: /img
  static_dir: flyingsim/static/img

- url: /css
  static_dir: flyingsim/static/css

- url: /flash
  static_dir: flyingsim/static/flash

- url: /js
  static_dir: flyingsim/static/js


- url: /.*
  script: main.py