application: flyingsim
version: 2
runtime: python
api_version: 1

handlers:
- url: /img
  static_dir: flyingsim/static/img

- url: /css
  static_dir: flyingsim/static/css

- url: /flash
  static_dir: flyingsim/static/flash

- url: /js
  static_dir: flyingsim/static/js

- url: /favicon.ico
  static_files: flyingsim/static/img/favicon.ico
  upload: flyingsim/static/img/favicon.ico
  
- url: /crossdomain.xml
  static_files: flyingsim/static/flash/crossdomain.xml
  upload: flyingsim/static/flash/crossdomain.xml

- url: /sitemap.txt
  static_files: flyingsim/static/sitemap.txt
  upload: flyingsim/static/sitemap.txt

- url: /robots.txt
  static_files: flyingsim/static/robots.txt
  upload: flyingsim/static/robots.txt

- url: /google6dd5946f87217236.html
  static_files: flyingsim/static/google6dd5946f87217236.html
  upload: flyingsim/static/google6dd5946f87217236.html
  

- url: /.*
  script: main.py